### ISSUE TITLE
Spiderdiagram is not shown

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/gerbil#101]
I want to see the spider diagrams again at the experiment over view. 

It is not working for Chrome Version 46.0.2490.80 (64-bit)

http://stackoverflow.com/questions/22557669/svg-added-to-dom-using-javascript-is-not-visible

**Comment by MichaelRoeder** [comment]
fixed with commit 813e7814129f3b25512a99b94d2983c2cd44aa87
