### ISSUE TITLE
AIDA webservice

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/gerbil#107]
Use AIDA webservice.

**Comment by MichaelRoeder** [comment]
I need more details for that :stuck_out_tongue:

**Comment by RicardoUsbeck** [comment]
as discussed here http://www.mpi-inf.mpg.de/departments/databases-and-information-systems/research/yago-naga/aida/ and here http://www.mpi-inf.mpg.de/departments/databases-and-information-systems/research/yago-naga/aida/webservice/. 

After talking to the main programmer we should use the following URL as endpoint 
https://gate.d5.mpi-inf.mpg.de/aida/service/disambiguate

**Comment by jangso417** [comment]
The URL is not available now.
https://gate.d5.mpi-inf.mpg.de/aida/service/disambiguate

**Comment by RicardoUsbeck** [comment]
Good morning @hoffart, any ideas?

**Comment by hoffart** [comment]
Looking into it - as alternative it might make sense to adapt the code to use https://github.com/ambiverse-nlu/ambiverse-nlu (you need to set it up yourself though)
