### ISSUE TITLE
D2KB how to handle NIL Links

### ISSUE THREAD

**Issue by dedcode** [AKSW/gerbil#110]
Hi,
What is Gerbil expecting when the annotator is not able to link the mention?
itsrdf:taIdentRef NIL . 
or nothing?
This case is not documented though it's part of D2KB task.
Thanks.

**Comment by MichaelRoeder** [comment]
Hi,

the task description as well as the example describe what is expected in this case. Please take a look at https://github.com/AKSW/gerbil/wiki/D2KB#task

Cheers,
Michael
