### ISSUE TITLE
Ever changing Wikipedia, and deprecated links

### ISSUE THREAD

**Issue by dedcode** [AKSW/gerbil#111]
The currently used MSNBC dataset contains wikipedia links that are no longer existing, became redirects or disambiguation pages. This is also the case for AQUAINT and ACE04.

This explains de very low results of good annotators such as Babelfy or NERD (http://gerbil.aksw.org/gerbil/experiment?id=201601200001)

State of the art approaches are achieving much higher results using corrected data, e.g. http://dl.acm.org/citation.cfm?id=2661887

* Could you consider using the corrected data from:
http://www.cs.ualberta.ca/~denilson/data/deos14_ualberta_experiments.tgz

or (and), 

* Can you indicate the date of the appropriate wikipedia/dbpedia dumps to use with a given dataset?

Thanks !

**Comment by MichaelRoeder** [comment]
We are aware of this problem. There is a discussion in #102 about this and other problems and how we want to tackle them.

* Thank you very much for this link. We will take a look at the data and discuss whether we can use it.
* We are aiming at the problem on another way. We try to update the datasets automatically to the current versions of DBpedia and Wikipedia. Additionally, we have started a project that will increase the quality of all datasets in GERBIL. Both is described in #102.

Cheers,
Michael
