### ISSUE TITLE
xLisa

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/gerbil#113]
Investigate the xLisa framework and the possibility to put it into the GERBIL framework

**Comment by TortugaAttack** [comment]
Tried a little bit with xLisa and i am pretty sure it is possible to put in Gerbil.
I would start beginning on that one.

**Comment by TortugaAttack** [comment]
Finished. 
Only needs to change the constraints for C2KB, A2KB, D2KB,.. so it does do what it should do 
and write a JUnit test
