### ISSUE TITLE
Missing files when downloading gerbil_data.zip

### ISSUE THREAD

**Issue by estefaniaotero** [AKSW/gerbil#114]
Got a set of exceptions while trying to load files under the directory ${org.aksw.gerbil.DataPath}/resources/hierarchies, because directory "hierarchies" and files under it does not exist (CollectionsLite.owl.xml, Conceptualization.owl.xml, d0.owl.xml, DUL.owl.xml, ontopic.owl.xml, Roles.owl.xml, Supplements.owl.xml).
This set of exceptions are obtained when I do a simple mvn clean tomcat:run, errors are thrown by org.aksw.gerbil.web.config.RootConfig.

**Comment by MichaelRoeder** [comment]
Hi,

Did you download and extract the latest gerbil_data.zip file from here: https://github.com/AKSW/gerbil/releases/download/V1.2.1/gerbil_data.zip ?

If the `gerbil_data` folder is not in the directory of the gerbil project, you will have to set `org.aksw.gerbil.DataPath` in `src/main/properties/gerbil.properties`.

Cheers,
Michael

**Comment by estefaniaotero** [comment]
Hi, 
Thanks for your response, I downloaded and extracted the gerbil_data.zip, but I didn't notice that it was for the wrong version. I used the link in the wiki page: https://github.com/AKSW/gerbil/wiki/How-to-setup-GERBIL and data is for other version (1.1.3). 

Thanks again for the fast response!

**Comment by MichaelRoeder** [comment]
Hi,

sorry for the confusion that the wrong link has caused. I fixed this problem.

Cheers,
Michael
