### ISSUE TITLE
how to calculate the precision and recall

### ISSUE THREAD

**Issue by chabmed** [AKSW/gerbil#119]
Hi,
i tried to find how gerbil calculate the precision and recall for Entity Recognition and D2KB
because what i know is that if a mention count as a false positive it affect the precision for entity Recognition so it will affect also the precision for D2KB. So the precision for the entity Recognition will be always higher than  precision for D2KB but when i tested with gerbil in many cases the D2KB precision was higher.
And another question about the result
First Line 
Second Line Entity Recognition
Third Line D2KB
So the first line represents the average of each column for the two other lines ?
Thank you,
Mohamed

**Comment by RicardoUsbeck** [comment]
Please have a first look at our new publication 
GERBIL’s New Stunts: Semantic Annotation Benchmarking Improved by Michael Röder, Ricardo Usbeck, and Axel-Cyrille Ngonga Ngomo (http://svn.aksw.org/papers/2016/ISWC_Gerbil_Update/public.pdf ) where we explain large parts. 
Second, basically yes but it is not the average for the A2KB task but the task itself separately.

**Comment by chabmed** [comment]
Hi,
sorry but there is no details in the article about how Gerbil calculate each step. 
Thanks 
Mohamed

**Comment by MichaelRoeder** [comment]
Hi Mohamed,

I think we should separate your two questions to make it easier to discuss them.

1. Why are there three lines for an experiment?
The first line (with the empty experiment type) is the result of the A2KB experiment. This is calculated **independently** from the others.
(Only the OKE Task 1 experiment result is defined as the average of the sub task results)

2. As described in [this short paragraph](https://github.com/AKSW/gerbil/wiki/D2KB#handling-of-higher-order-annotators), the D2KB takes only those entities into account that are exactly matching the entity positions inside the gold standard. Thus, it is possible that the precision of the D2KB subtask is higher than the precision of the Entity Recognition subtask.

Does this answer your questions?

**Comment by chabmed** [comment]
Hi,
for the second question it's clear now , but for the first point about the result of A2KB how it is calculated?
Thank you,
Mohamed

**Comment by MichaelRoeder** [comment]
As described in _[GERBIL - General Entity Annotation Benchmark Framework](http://www.bibsonomy.org/bibtex/26c11b58df0dc5ad5a350fbfb01334bfb/aksw)_ to be counted as true positive, an entity has to match a) the position and b) the meaning of the expected entity.

**Comment by chabmed** [comment]
hi,
yes it's clear, thank you for your quick reply,
Mohamed
