### ISSUE TITLE
Quick study about user behaviour

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/gerbil#122]
Find out if paper which cite a GERBIL paper (excluding self-references) are actually using the experiment URL.

**Comment by MichaelRoeder** [comment]
Please use this form for the task: https://docs.google.com/spreadsheets/d/1zucChdiDYO7M9pfYu9fklu97mW8ZXbm25Q7ijxA8NQc/edit#gid=0

**Comment by TortugaAttack** [comment]
_Suggestion:_ 
As its way to much effort to do that in person, i will do that automatically:

1.  download next pdf 
2.  convert pdf to a format which can be parsed
3.  parse the file for the gerbil.aksw.org/gerbil/..expriment url 
4.  put it in the shared form

This for every pdf.

Is that acceptable?

**Comment by MichaelRoeder** [comment]
You can do it in this way. However, I think a manual search might be faster than parsing all the PDFs. But it is up to you to decide as long as we get the information that we would like to have.

**Comment by TortugaAttack** [comment]
done

**Comment by MichaelRoeder** [comment]
Can you please try to access the missing publications by searching for the authors? The first missing publication for example can be downloaded from the first authors website http://hasibi.com/publications/

**Comment by TortugaAttack** [comment]
done. 
Still one missing though: Machine-Crowd Annotation Workflow for Event Understanding Across Collections and Domains by Oana Inel
I start to think it is not available for free. :/

**Comment by MichaelRoeder** [comment]
It seems like it was presented at the Doctoral Symposium of the ESWC. Thus, I might have it on the conference USB stick. I will check that tomorrow.

**Comment by MichaelRoeder** [comment]
Found it on the stick and added the infos to the table.
