### ISSUE TITLE
NIF Upload does not work

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/gerbil#124]
Dear dev-team ;)

uploading a NIF file does not work anymore if I first click the select file button> select a file> hit open and then type in the name. You have to type the name first and the select the file. this is sometimes uncomfortable. If I do it in the wrong order I have to reload the page. Thanks for solving this issue in advance.

**Comment by TortugaAttack** [comment]
i actually do not have to reload the page. (which i guess is the actual problem) 
Maybe it was a browser problem? :/

**Comment by RicardoUsbeck** [comment]
Seemed to be a browser-based problem
