### ISSUE TITLE
[dataset] Microposts 2016

### ISSUE THREAD

**Issue by MichaelRoeder** [AKSW/gerbil#132]
Yet another microposts dataset ;)

http://microposts2016.seas.upenn.edu/challenge.html

**Comment by TortugaAttack** [comment]
as far as i can see: not available for public right now

**Comment by giusepperizzo** [comment]
The NEEL 2016 tweet ids along with the annotations will be publicly released soon with the proceedings of the challenge. You can then collect the tweet contents via querying the Twitter API.

Anyway, you can *now* have access to the GS by downloading the agreement https://goo.gl/idFdyP, signing it, and sending the pdf to giuseppe.rizzo@ismb.it and marieke.van.erp@vu.nl , as reported http://microposts2016.seas.upenn.edu/challenge.html .
We will share the GS that contains tweet ids, tweet contents, and annotations. 

This GS should be only used for research purposes, and any further sharing will be an infringement of the Twitter ToS (as it was for past editions of the NEEL series of challenges).

**Comment by MichaelRoeder** [comment]
@giusepperizzo Thanks for pointing that out. Thus, we will add the adapter and the dataset to the instance that runs on our server but we won't upload the dataset to github. (We handle the AIDA/CoNLL datasets in the same way)

@RicardoUsbeck As the head of the GERBIL project you have to do the signing. @TortugaAttack and me are only developers :stuck_out_tongue:

@TortugaAttack Please prepare a simple tool with which we can retrieve the tweets from the Twitter API.

**Comment by giusepperizzo** [comment]
We've been used and still use the following tweet collector https://github.com/aritter/twitter_download

Beware that tweets are volatile, thus a collection you do at t0 may have different tweets than if done at t1 (with t0 != t1). Thus the annotation results won't be really comparable if not cache of the tweets is provided. 

Additionally, we should discuss how to ensure that the GERBIL benchmark mechanism does not infringe the Twitter ToS, since we leave systems to query the data stored in the official GERBIL instance. This in the past has been handled by avoiding caching datasets with a licence different than the fully public ones.

**Comment by MichaelRoeder** [comment]
I just realized that I have missunderstood a part of your first tweet. Since the GS contains the tweet content we do not need to download the tweet contents by ourselfs and, thus, avoid the problem of tweets being volatile.
@TortugaAttack forget what I wrote above :grinning:

Regarding the licence, our users have to check that they agree to our [disclaimer](https://github.com/AKSW/gerbil/wiki/Disclaimer) at the bottom of our [configuration page](http://gerbil.aksw.org/gerbil/config). The disclaimer clearly states, that systems are not allowed to store any data that is sent to them. Do you think that this is sufficient to match the Twitter ToS?

**Comment by giusepperizzo** [comment]
Clear enough, thanks

**Comment by RicardoUsbeck** [comment]
@TortugaAttack What is the status here?

**Comment by TortugaAttack** [comment]
i do not have the dataset, does some of you have it. Otherwise i will fill out the signing or so :)

**Comment by RicardoUsbeck** [comment]
Have a look at https://drive.google.com/drive/folders/0B7oVKINifZRDejVmdlh6dWdBZUU?zx=wzlnhh617woh . License was signed by me already

**Comment by TortugaAttack** [comment]
done
