### ISSUE TITLE
Create DBpedia index for sameAs retrieval

### ISSUE THREAD

**Issue by MichaelRoeder** [AKSW/gerbil#135]
Based on the changes made for #134 the sameAs retrieval could be enhanced by creating an index for databases that are used often, e.g., DBpedia. Instead of retrieving the information via HTTP the system could use a local index to retrieve additional URIs.

This could be enhanced by combining it with the caching, i.e., adding cache entries that are never getting old.

However, the usage of a local DBpedia index should be optional. The system should still work without this index.

**Comment by MichaelRoeder** [comment]
Implemented by @TortugaAttack 
will be ported to QA with #161

**Comment by MichaelRoeder** [comment]
Added the (optional) download of the index to the start script with cf571912289cce9901171f90645fd27dc4572ff3

**Comment by TortugaAttack** [comment]
could you test it?
and if so, can we close this 

Port in #161 done.

**Comment by MichaelRoeder** [comment]
It loks very nice :)

One final enhancement could be done to the JUnit test. At the moment, the index is created in a local folder called `test` (https://github.com/AKSW/gerbil/blob/version1.2.5/src/test/java/org/aksw/gerbil/semantic/sameas/index/IndexerTest.java#L21). That leads to the creation of this folder in the project folder every time the tests are executed, right?

A temporary folder would be better. You could use something like I have done at https://github.com/AKSW/Palmetto/blob/version0.1.2/palmetto/src/test/java/org/aksw/palmetto/corpus/lucene/creation/PositionStoringLuceneIndexCreatorTest.java#L89

**Comment by TortugaAttack** [comment]
changed it :)
