### ISSUE TITLE
Experiments are not running

### ISSUE THREAD

**Issue by sebastianarnold** [AKSW/gerbil#137]
Hi Ricardo,

I was about to start an experiment with the following configuration:

Type: Entity Recognition
Matching: Ma - strong annotation match 
e.g. FOX on KORE50: http://gerbil.aksw.org/gerbil/experiment?id=201607130007

The experiment is not starting, neither on my local installation (current GIT head, v1.2.4) nor on the demo. There are no requests sent to the annotators. The overview page displays "The experiment is still running."

Best,
Sebastian

**Comment by MichaelRoeder** [comment]
Hi,

how long do you have been waiting? GERBIL tries to a) checks the validity of the URIs in the gold standard and b) [retrieve additional URIs](https://github.com/AKSW/gerbil/wiki/URI-matching) for the entities mentioned. This increases the quality of the evaluation. Unfortunately, it increases the runtime as well (at least in the first experiment, since the retrieved information are cached for later reusage).

If you do not want to wait for these steps, you can deactivate them as described [here](https://github.com/AKSW/gerbil/issues/130). However, this might lead to lower scores for your annotation system.

Cheers,
Michael

**Comment by sebastianarnold** [comment]
Hi Michael,

thanks for the hint, but I don't think that this is the issue here. The experiment mentioned above is still running on your server (11 hours, only 50 sentences in KORE50) and Entity Recognition does not include URIs.

Best,
Sebastian

**Comment by MichaelRoeder** [comment]
Hi,

unfortunately, the experiment type is not taken into account for the preprocessing. Thus, this step will be executed. However, 11 hours are too long for that. It should take only some minutes for KORE50.

Could you please open the web page of your gerbil instance running on your server, append `/running` (http://someIpAndPort/gerbil/running) and post the printed stack trace here?

Cheers,
Michael

**Comment by MichaelRoeder** [comment]
Hi,

I took a look at our server. At the Moment, there are 352 (!) Experiments running and the server can handle only 20 of them in parallel (and some of them are currently blocked by the preprocessing). It will take some time until the server has processed them.

Cheers,
Michael

**Comment by MichaelRoeder** [comment]
@TortugaAttack We should add the number of running experiments with a hint that it might take some time if the number is larger than the available number of workers.

**Comment by sebastianarnold** [comment]
Hi Michael,

on my local machine, GERBIL shows no progress even after hours when URI matching is enabled. My annotator is not getting any requests. However, it works fine when URI matching is disabled. Do you see any progress on your server? Have some of the 284 experiments finished in the meantime? Here is the stack trace with URI matching enabled (not changing after reloads):

```
eTConfig("XXXXX","KORE50","ERec","STRONG_ANNOTATION_MATCH")
state=RUNNABLE
progress=null
java.net.SocketInputStream.socketRead0(Native Method)
java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
java.net.SocketInputStream.read(SocketInputStream.java:170)
java.net.SocketInputStream.read(SocketInputStream.java:141)
org.apache.http.impl.conn.LoggingInputStream.read(LoggingInputStream.java:87)
org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
org.aksw.gerbil.dataset.check.impl.HttpBasedEntityChecker.entityExists(HttpBasedEntityChecker.java:63)
org.aksw.gerbil.dataset.check.impl.EntityCheckerManagerImpl.checkUri(EntityCheckerManagerImpl.java:135)
org.aksw.gerbil.dataset.check.impl.FileBasedCachingEntityCheckerManager.checkUri(FileBasedCachingEntityCheckerManager.java:154)
org.aksw.gerbil.dataset.check.impl.EntityCheckerManagerImpl.checkMeaning(EntityCheckerManagerImpl.java:84)
org.aksw.gerbil.dataset.check.impl.EntityCheckerManagerImpl.checkMarkings(EntityCheckerManagerImpl.java:64)
org.aksw.gerbil.dataset.AbstractDatasetConfiguration.getPreparedDataset(AbstractDatasetConfiguration.java:79)
org.aksw.gerbil.dataset.SingletonDatasetConfigImpl.getPreparedDataset(SingletonDatasetConfigImpl.java:50)
org.aksw.gerbil.dataset.AbstractDatasetConfiguration.getDataset(AbstractDatasetConfiguration.java:50)
org.aksw.gerbil.execute.ExperimentTask.run(ExperimentTask.java:101)
org.aksw.simba.topicmodeling.concurrent.workers.WorkerImpl.run(WorkerImpl.java:44)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
```

**Comment by MichaelRoeder** [comment]
Hi Sebastian,

the stack trace looks fine and it does not seem to be stuck. It simply takes time to retrieve the URI sets. But since it works for you without recognition you should get the evaluation results you wanted to have.

The server has finished ~50 tasks and has still 232 to compute.

Cheers,
Michael

**Comment by TortugaAttack** [comment]
Okay, There will be now a Text at the experiment window which contains the following: 
1. if your  Experiments are waiting to be executed of  a worker (in red): "Experiments could take a while! No-Of-Exp-Before-yours Experiments before yours on No-Of-Workers Worker"
2. if your first Experiment will be executed right now:  Nothing additional
3. if all your Experiments are finished: "your Experiments are finished"

**Comment by TortugaAttack** [comment]
Due to #135 can this issue be closed?

**Comment by RicardoUsbeck** [comment]
I think it would be good to have only 135
