### ISSUE TITLE
[QA] Indicate system location

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/gerbil#138]
Indicate whether a system has been evaluated using a dump or a live web demo. This is important to see whether the system can be used by the community (webservice has a higher chance of using than a dump file)

**Comment by MichaelRoeder** [comment]
An uploaded file dump should already get a postfix like " (Uploaded)". Can you please check this first, before thinking about another solution? It should already have been implemented in the AdapterManager class.

**Comment by TortugaAttack** [comment]
Yep, 
uploaded dumps has the postfic " (uploaded)" (http://gerbil.aksw.org/gerbil/experiment?id=201607250001)

**Comment by TortugaAttack** [comment]
Uploaded Annotators have the postfix " (uploaded)" while datasets results into a blank abyss (http://gerbil-qa.aksw.org/gerbil/experiment?id=201607250003) 
In gerbil itself, uploaded datasets have the postfix.

**Comment by MichaelRoeder** [comment]
@TortugaAttack Do you tried to upload a NIF file or why did it crash?

@RicardoUsbeck: However, it is implemented in the same way as it is done for uploaded dataset dumps (in this line https://github.com/AKSW/gerbil/blob/QuestionAnswering/src/main/java/org/aksw/gerbil/web/config/AdapterManager.java#L161). Does this covers the functionality you expected?

**Comment by TortugaAttack** [comment]
So actually i selected the wrong file. Still though i tried it with the test and train xml files from qald4 and same blank screen

**Comment by RicardoUsbeck** [comment]
@D063520 That's actually what we discussed, isn't it?

**Comment by RicardoUsbeck** [comment]
@TortugaAttack the blank screen is really weird. Should work with both files.

**Comment by D063520** [comment]
Yes, this is what where speaking about.
