### ISSUE TITLE
REDEN dataset and annotator

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/gerbil#140]
Here (https://csimq-journals.rtu.lv/article/view/csimq.2016-7.04/pdf_6) authors describe a new dataset for library since as well as an annotator. Check how to use both in GERBIL. Are they usable at all in GERBIL?

**Comment by MichaelRoeder** [comment]
Seems to be a french corpus and a french annotator.

**Comment by RicardoUsbeck** [comment]
Since this language-based task is currently not requested by the community, we will postpone its implementation to a later point of time and close the issue for now.
