### ISSUE TITLE
Cache contains wrong information

### ISSUE THREAD

**Issue by filipdbrsk** [AKSW/gerbil#142]
With @MichaelRoeder we found out that the cache for the MSNBC dataset contains wrong information with respect to dereferencing. This can be checked by executing the tests for sameAsRetrieval, where this test fails: https://github.com/AKSW/gerbil/blob/master/src/test/java/org/aksw/gerbil/semantic/sameas/SameAsRetrievalTest.java#L55-L56.

Probably the last time, GERBIL updated this information, there might have been some network issues that made it impossible to retrieve this information. At this point the obvious solution seems: deleting the cache files and retrieving the links again.

I am not sure whether this affects other datasets, but at least for MSNBC the results for D2KB and related tasks are probably not correct at the moment. Although re-generating the cache takes a while, I think it is very important to do this and update the results soon.

**Comment by MichaelRoeder** [comment]
@TortugaAttack: I deleted the cache files and restarted the service. Could you please start the experiments for the different dataset x annotator combinations during the next days? Please make sure that not too many experiments are started at once especially because the server might have to be shutdown on monday.

Thanks :smile:

**Comment by TortugaAttack** [comment]
So i did a rerun: 
and http://gerbil.aksw.org/gerbil/experiment?id=201608220017 (WAT runs initial) 
http://gerbil.aksw.org/gerbil/experiment?id=201608230010 (WAT as cached) 
is not the same.

**Comment by MichaelRoeder** [comment]
Thanks for rerunning the experiments and pointing out the difference :)
