### ISSUE TITLE
gerbil.nif.transfer ClassCast Exception

### ISSUE THREAD

**Issue by JonathanHuthmann** [AKSW/gerbil#150]
Following: https://github.com/AKSW/gerbil/wiki/Generating-a-NIF-dataset-using-Java
using:  gerbil-nif-transfer version 1.2.2-jena3.1

i tried to use TypedSpanImpl, came up with this:

	public static void main(final String[] args) {
		Document document = new DocumentImpl("Hello World");
		document.addMarking(new TypedSpanImpl(0, 4, new HashSet<String>()));

		List<Document> documents = new ArrayList<>();
		documents.add(document);

		// Writing our new list of documents to a String
		NIFWriter writer = new TurtleNIFWriter();
		String nifString = writer.writeNIF(documents);
		System.out.println(nifString);
	}

which throws:

	TypedSpanImpl cannot be cast to org.aksw.gerbil.transfer.nif.data.TypedNamedEntity
    
so, TurtleNIFWriter expects from all Markings to be an TypedNamedEntity. Is this expected behavior?

**Comment by MichaelRoeder** [comment]
No, this seems to be a bug.

**Comment by MichaelRoeder** [comment]
Should be fixed now. Please pull the changes and check it for your use case.

If it is fixed, close this issue. Otherwise, write the new error, that occrurs.

**Comment by JonathanHuthmann** [comment]
Works. Thank you for fixing it so fast.
