### ISSUE TITLE
[QA] debug QANARY

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/gerbil#156]
If I use the eQALD  JSON based QANARY endpoint (http://wdaqua-qanary.univ-st-etienne.fr/gerbil) using parameter query and some question, I am not sure the answer matching for STRING, RESOURCE, DATE and NUMBER works. Please investigate and write unit tests per answer type for this endpoint.

**Comment by TortugaAttack** [comment]
While some of the answers in the older QALD questions are outdated (e.g. numbers of employees and such) 
Dates work as far as i saw. (Correct dates were correctly matched)
Numbers, Resources, 
The only problem occurred during qald3-train was that in the responding JSON true was not be matched as correct if the answer is True. (same with false/False)
Obviously ask questions have a high impact on the f measure. 
Will fix this, so true/false will be replaced with True/False. 

Further on gerbil-qa can now produce a csv table with the annotator answers, as well as the golden std the true positives, false positives, false negatives, precision, recall, f-measure for each question
As well as the macro and micro f-measure for all questions. 
This is of course optional and can be taken out of the code if whished. ;)

**Comment by RicardoUsbeck** [comment]
Hi, sounds awesome. 

1) So I guess we should fix the true/True => True mapping, so that we do not match strings but convert them first to booleans. To be safe for future datasets.
2) Afterwards, it would be nice to have a mechanism which tests whether SPARQL answerset and gold answerset are the same and if **not** so uses the SPARQL answerset against the KB. 
3) I am really eager to have this CSV producer in the code, please add if @MichaelRoeder is ok with it. 

Thanks!

(Please reference this issue in the commits)

**Comment by MichaelRoeder** [comment]
Since the questions are open source I don't see anything that could cause problems with the CSV producer. Is the result part of the GUI or is it only for debugging?

**Comment by TortugaAttack** [comment]
one Update on Dates: QALD-5 dates are yyyy-mm-dd+02:00 which was fine in the past dbpedia but will now be answer from dbpedia as yyyy-mm-dd 

1) I think it will be a Problem which stays as long as DBpedia is changing the formats (also the problem with the outdated answers), hence i would suggest we update the answers with every big dbpedia update? 
Still i can/will do the mapping for boolean and dates.

2.) will do that. 
3.) nice, it is currently only for debugging, but can be build into the GUI (would need to rewrite the code a bit though)

**Comment by MichaelRoeder** [comment]
Regarding 1) wouldn't it be easier to transform dates or timestamps into one common internal format? I think you can parse `Date` objects from a given String by supplying a String that defines the format. Thus, you could analyze the answer string, check whether it matches one of the known date strings and apply the correct parsing into an internal Date object. Than we could work with the Date objects instead of Strings that have to be transformed into each other...

**Comment by RicardoUsbeck** [comment]
Also, since we always pull the QALD data from another repo on every release a static "curation" of the answers would be rendered senseless

**Comment by TortugaAttack** [comment]
aah okay, yeah that makes it useless. 
well will do booleans/dates as Boolean/Date objects as you suggested. ;)

**Comment by TortugaAttack** [comment]
**Update**
1. Is finished + Unit Tests for each Answer, needs to be tested though, will do test as soon as qanary is up again. If it works i will commit this into NLIWOD and here. 
2. Needs to be done. But here i have a few questions below
3. is completely rewritten, and can be put more easily to the GUI if wished. (will commit as soon as completely tested)

**Questions 2.**
1.  Should this be always tested if the answers are not the same. e.g. if annotators answer is a resource but the golden std is a number, obviously the query is wrong. No Need to test. Thus we only need to test, if answer types are the same and only the answers differ. Or do i forget something here?
2. This could lead to a lot of time spending querying if the QASystem is not so good. But we could cache the answers, so we do not need to querying the same questions always again. Does something speak against caching?

**Comment by RicardoUsbeck** [comment]
Hi,

for question 2.1) That sounds complete to me for now for 2.2) Caching for 7 to 14 days sounds reasonable

**Comment by TortugaAttack** [comment]
will close this issue and open another one, for subtask 2)
