### ISSUE TITLE
File upload for Typed Entity experiment

### ISSUE THREAD

**Issue by renespeck** [AKSW/gerbil#157]
Hi, 
I created a document with the help of this line: https://github.com/AKSW/gerbil/blob/master/src/test/java/org/aksw/gerbil/execute/OKEChallengeTask1ETTest.java#L146, then I upload the file for the Entity Typing experiment within the GUI of GERBIL. The integrated annotators are not able to work with that file. That means the value of F1, Recall,... are all '?'.

What am I doing wrong?

**Comment by MichaelRoeder** [comment]
Unfortunately, uploaded datasets for Entity Typing are not processed correctly. This is fixed in version 1.2.5. The pre-release version can already be accessed in this branch https://github.com/AKSW/gerbil/tree/version1.2.5
