### ISSUE TITLE
 ERD14 and GERDAQ

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/gerbil#158]
Investigate the datasets  ERD14 und GERDAQ for entity recognition in queries

**Comment by RicardoUsbeck** [comment]
More information about the datasets can be found here http://sigir.org/files/forum/2014D/p063.pdf and http://acube.di.unipi.it/datasets/ .

For general information look at https://github.com/AKSW/gerbil/wiki/How-to-add-a-new-Dataset

**Comment by MichaelRoeder** [comment]
Fixed with d7888b0d2b3cffe9ac28ccd77903bc193f6e350d and 8425da1ead3faa0a690e17661c47ba2176ccad6b
