### ISSUE TITLE
[QA] Using Lucene for SameAs Retrieval

### ISSUE THREAD

**Issue by TortugaAttack** [AKSW/gerbil#161]
Same as Gerbil, the SameAs Retrieval takes a lot amount of time, using lucene indexing would help. 
It is implemented in Gerbil and could be easily merged into gerbil-qa.
(Of course this would be optional and will only be used if the user wants to)

Also lucene would only be needed initially. So i am not quite sure if the caching is  a problem in the deployment. 

If everyone is fine with it, i would merge the files.

**Comment by RicardoUsbeck** [comment]
Sounds like a good idea to me! Thanks for working on it!

**Comment by TortugaAttack** [comment]
done.
