### ISSUE TITLE
[QA] use SPARQL Query of file if answersets differ

### ISSUE THREAD

**Issue by TortugaAttack** [AKSW/gerbil#164]
Create a mechanism which uses the SPARQL query of the questions file (if available) if the annotator answerset and the golden standard anserset differs. 

1. Should this be always tested if the answers are not the same. e.g. if annotators answer is a resource but the golden std is a number, obviously the query is wrong. No Need to test. Thus we only need to test, if answer types are the same and only the answers differ.
2. This could lead to a lot of time spending querying if the QASystem is not so good. But we could cache the answers, so we do not need to querying the same questions always again. 
Cacheing should be 7 to 14 days

**Comment by TortugaAttack** [comment]
Done but not as mentioned above. 
If the `gerbil.properties` file contains `org.aksw.gerbil.dataset.impl.qald.deriveUri=http://dbpedia.org/sparql` the golden Answer will be derived by DBpedia (or any Endpoint you specified) 
(No caching, no answerType Test)

Commits: in NLIWOD [2fb662b7](https://github.com/AKSW/NLIWOD/commit/2fb662b7fbaca226c599cc1c5a4541b864c78560) and adjusted in commit [d102c81](https://github.com/AKSW/gerbil/commit/d102c8141d0916b4882d1958d02146dc060afaae)
Can be used by using the `org.aksw.gerbil.dataset.impl.qald.deriveUri=http://dbpedia.org/sparql` in the `gerbil.properties` file

**Comment by RicardoUsbeck** [comment]
But if there is none deriveURI it uses the answers from the files?

**Comment by TortugaAttack** [comment]
exactly. 
Also if there is no SPARQL Query, it will use the answers from file.
