### ISSUE TITLE
[dataset] Implement a wrapper for senseeval datasets

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/gerbil#17]
@Andrea Moro: Add a Senseeval wrapper and make sure the dataset is openly available and the licence is ensured since we want only open datasets in GERBIL.

**Comment by TortugaAttack** [comment]
Is finished. I will commit it but first without adding it to the dataset.properties.

**Comment by RicardoUsbeck** [comment]
What is the status here?

**Comment by TortugaAttack** [comment]
is there any license information i can add to the info site? 
The code itself is finished and commitet, and will be added right now to the properties. I will close the issue as soon as i can update the licence informations :)

**Comment by RicardoUsbeck** [comment]
@andrea8moro What is the license here?

**Comment by TortugaAttack** [comment]
found two links deep in the web, where senseval2 and senseval3 data are under Public Domain. 

Thus i updated the licence info for both and put the links where i found the information beneath.
