### ISSUE TITLE
TAC-KBP 2010 & 2009 datasets

### ISSUE THREAD

**Issue by octavian-ganea** [AKSW/gerbil#176]
Hi all,

For local D2KB approaches, TAC KBP 2009 and 2010 datasets were used by a few researchers, e.g. [1,2,3,4]. It would be great if these could be integrated with Gerbil as well. These datasets seem to be missing from the official pages [5] and [6]. If anyone knows if this data can be found online, it would be of great help to post the link here.

[1] http://ir.hit.edu.cn/~dytang/paper/ijcai2015/ijcai15-yaming.pdf
[2] http://www.aclweb.org/anthology/P13-2006
[3] https://arxiv.org/pdf/1601.01343.pdf
[4] http://www.aclweb.org/anthology/C10-1032
[5] https://catalog.ldc.upenn.edu/byyear#2010
[6] http://tac.nist.gov/data/index.html

**Comment by rtroncy** [comment]
You need to register and sign agreement documents to get the data, but the documents you sign prevent you to redistribute the data so you will hardly be able to give access to these datasets via Gerbil

**Comment by DiegoMoussallem** [comment]
@octavian-ganea , I have gotten in touch with them(TAC group) and they said the data sets are only for participants or you can "wait" for our release. So, I have written an email to LDC group and they sent me a letter for two datasets only (1000 euros each) and they said the same things which Heng Ji(TAC KBP Challenge organizer). Moreover, @rtroncy is right, we can't redistribute which is IMHO very sad.

**Comment by octavian-ganea** [comment]
Thanks. I also tried to contact LDC and sent the agreement documents. The answer I received from them:

"Unfortunately this evaluation is closed for joining. The only TAC KBP data sets we have publicly available are as follows:
·         LDC2014T16 TAC KBP Reference Knowledge Base
·         LDC2016T26 TAC KBP Spanish Cross-lingual Entity Linking - Comprehensive Training and Evaluation Data 2012-2014
I do apologize."

**Comment by DiegoMoussallem** [comment]
yeah, I've gotten the same response. That's bad because we can't compare our approach to many scientific papers from the linguistic community.

**Comment by RicardoUsbeck** [comment]
Well, let's hope for the best in the future and if anyone find's another TAC KBP dataset to use, we can reopen this issue.
