### ISSUE TITLE
To implement  Coheel - EL system

### ISSUE THREAD

**Issue by DiegoMoussallem** [AKSW/gerbil#179]
code: https://github.com/stratosphere/coheel
paper: https://hpi.de/fileadmin/user_upload/fachgebiete/naumann/publications/2016/jwskg16.pdf

**Comment by RicardoUsbeck** [comment]
Do they have a webservice?

**Comment by DiegoMoussallem** [comment]
Waiting the author' answer.

**Comment by MichaelRoeder** [comment]
Even if they don't have a webservice, it might be interessting for HOBBIT (if we can start the annotator easily in docker)

**Comment by DiegoMoussallem** [comment]
Closing it due to no response from authors.
