### ISSUE TITLE
Replace *Mapping classes

### ISSUE THREAD

**Issue by spinner0815** [AKSW/gerbil#22]
I would like to replace the *Mapping.java (org.aksw.gerbil.utils) with CSV Files.  This file could than be loaded into a database. 
So to add a Annotator or Datasets it should be more easy. 
Also a more dynamic way for loading Annotators/Datasets via the frontend should than be possible. The added Annotators/Datasets could than be stored into a database and in the CSV Files.

**Comment by MichaelRoeder** [comment]
Has been fixed in version 1.2.0
