### ISSUE TITLE
[dataset] UMBC dataset wrapper

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/gerbil#44]
Write a wrapper for the UMBC dataset. 
Annotate the license, experiment type and language. 
Give provenance.
Update https://github.com/AKSW/gerbil/wiki/Licences-for-datasets

**Comment by RicardoUsbeck** [comment]
http://ebiquity.umbc.edu/_file_directory_/papers/500.pdf

**Comment by TortugaAttack** [comment]
done
