### ISSUE TITLE
Transform wikipedia id central view point to URI central view point

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/gerbil#51]
The idea of this important step is to become knowledge base agnostic. Most datasets are annotated to some form of Wikipedia or DBpedia. Currently, we only support annotation to these systems. 

GOAL: transform each method to understand URIs. Annotate each corpus with its annotation knowledge base and each annotator with his capable annotations.

**Comment by MichaelRoeder** [comment]
Has been fixed in version 1.2.0
