### ISSUE TITLE
[dataset] Semeval 2013 wrapper

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/gerbil#55]
Implement Semeval 2013 wrapper.

Upload the dataset to dataset/semeval2013/ folder.

@andrea8moro Which licence does the dataset have?

**Comment by TortugaAttack** [comment]
I am not sure if the dataset still exists. at least the links in the google group are not up to date. :/

**Comment by TortugaAttack** [comment]
There are simply no markings in the dataset
I searched in the google forum because Task2 B has no topics in the dataset: 
There are only tweets

**Comment by MichaelRoeder** [comment]
Hi all,

this dataset seems to fit WSD, which we have not implemented, yet. Apart from that, I do not see a task from the list of challenge tasks (see the table "Areas of evaluation" at https://en.wikipedia.org/wiki/SemEval) that is interesting for GERBIL.

@RicardoUsbeck the table lists QA datasets for 2015 and 2016.

**Comment by RicardoUsbeck** [comment]
From my point of view, we can close this issue. We should keep in mind to ask Roberto Navigli to join HOBBIT with a WSD task.

@MichaelRoeder Thanks for the pointer
