### ISSUE TITLE
Wrong transformation of Micropost to GERBIL data structures

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/gerbil#81]
Obviously, all annotation services perform poor on the Micropost datasets. Looking at some log files of AGDISTIS I saw that the entities were randomly off their positions. Sometimes, even the lengths did not match. Please correct that.

**Comment by MichaelRoeder** [comment]
I tested it and found some small bugs that I could fix directly.

One of them was, that the Micropost2014 gold standard says, that there is a named entity, e.g., "Amy Winehouse". But the tweet contained a surface form containing one or more hashtags, e.g., "#Amy #Winehouse Is #Dead After a Suspected Drug Overdose  http://t.co/9KBWCeN via @YahooNews".

Now, the correct surface form ("#Amy #Winehouse") is identified and replaces the wrong surface form while loading the dataset.
