### ISSUE TITLE
[dataset] Microposts2015 wrapper

### ISSUE THREAD

**Issue by giusepperizzo** [AKSW/gerbil#82]
Write a wrapper for the Microposts2015 dataset. 
Annotate the license, experiment type and language. 
Give provenance.
Update https://github.com/AKSW/gerbil/wiki/Licences-for-datasets

**Comment by TortugaAttack** [comment]
I would add them if you can say where i can find the dataset :)

**Comment by MichaelRoeder** [comment]
I could finnd the [challenge description](http://scc-research.lancaster.ac.uk/workshops/microposts2015/challenge/index.html). However, I couldn't find the  training and evaluation datasets. @giusepperizzo Can you give us a hint, please?

**Comment by RicardoUsbeck** [comment]
Ping @giusepperizzo

**Comment by giusepperizzo** [comment]
#### Tweets + manual annotations
NEEL2015: please sign and send back to giuseppe.rizzo@ismb.it https://docs.google.com/document/d/1e6Eo7ZCJlPTTVuHKVlbpb72N0G7BzLfBWCVvUYcKlak sign 

NEEL2016: please sign and send back to giuseppe.rizzo@ismb.it
https://docs.google.com/document/d/1M7GsOWgyC_L6O9LYWGwVr2YcpxEa30CPDsHefVK-_TU

I'll then give access to the original set of tweets (to be only used for research purposes and they cannot be shared further -- as for CE2013, NEEL2014) and the set of human annotations. 

#### manual annotations
NEEL2015 http://ceur-ws.org/Vol-1395/microposts2015_neel-challenge-report/microposts2015-neel_challenge_gs.zip
NEEL2016 http://ceur-ws.org/Vol-1691/microposts2016_neel-challenge-report/microposts2016-neel_challenge_gs.zip

**Comment by RicardoUsbeck** [comment]
See mail ;)

**Comment by TortugaAttack** [comment]
done
