### ISSUE TITLE
macro F1 not a harmonic mean of macro recall and macro precision

### ISSUE THREAD

**Issue by kliegr** [AKSW/gerbil#87]
The macro F1 does not correspond to the harmonic mean of macro precision and macro recall in Gerbil 1.1.1. According to equation 3 in  the BAT framework paper [1], referenced from the Metrics section of the Gerbil paper [3], both micro and macro F1 measures should correspond to harmonic means of the respective precision and recall statistics. 

When doing further checks, I found out that the macro F1 does not correspond to the harmonic mean also in the earlier published  evaluations [2] performed with Gerbil 1.0.0.  For example, the macro F1 reported for NERD-ML on KORE50 dataset is 0.2095, macro precision is 0.2937 and macro recall 0.2283. The harmonic mean of 0.2937 and 0.2283 is 0.257. In  this case, the macro F1 does not lie between macro precision and recall.

It should be noted that _micro_ F1 on Gerbil output does corresponds to harmonic mean of micro F1 recall and precision.

[1] http://static.googleusercontent.com/media/research.google.com/cs//pubs/archive/40749.pdf
[2] http://gerbil.aksw.org/gerbil/experiment?id=201411100001
[3] http://svn.aksw.org/papers/2015/WWW_GERBIL/public.pdf

**Comment by MichaelRoeder** [comment]
Hi,

I am sorry to say, that the Macro F-measure definition in the paper of Cornolti et al. is wrong while their implementation inside the BAT-Framework is correct. So its not a bug, its a feature :D

The reason that the F1 can be lower than the precision and recall is, that all three Macro values are averages over precision, recall and F1 values calculated for every single document. 

Think of a dataset comprising two documents - document 1 contains 1 entity while document 2 contains 1000 entities. Lets say, there is an annotator getting the following values:
for document 1 it retrieves 1000 entites - the single correct entity an 999 wrong entities.
for document 2 it retrieves only 10 entities which are correct while 990 entities are missing.

For micro precision, recall and F1 we sum the true positive, false positives and true negatives up over all documents. tp=2, fp=999, fn=990, precision = 0.0108910891, recall=0,010989011, F1-score=0,0109398309

For macro precision, recall and F1 we calculate the values for each single document before calculating the averages over all documents.
document 1 tp=1, fp=999, fn=0, precision=1/1000, recall=1, F1-score = 0.001998002
document 2 tp=10, fp=0, fn=990, precision=1, recall=1/100, F1-score = 0.0198019802
the macro values are: precision=0.5005, recall=0.505, F1-score=0.0108999911

You can see that the F1-scores are different and that the macro F1-score is much lower than the macro precision and recalls.

Cheers,
Michael
