### ISSUE TITLE
Mavenized BAT-framework

### ISSUE THREAD

**Issue by marcocor** [AKSW/gerbil#90]
Dear GERBIL developers,
I have mavenized the BAT framework and uploaded it on the Maven Central Repository. You can now include it in your pom.xml with a simple:

```
<dependency>
    <groupId>it.unipi.di.acube</groupId>
    <artifactId>bat-framework</artifactId>
    <version>1.0</version>
</dependency>
```

Unfortunately, I had to change all package names from `it.acubelab.batframework.<x>` to `it.unipi.di.acube.batframework.<x>` in order to comply with Maven naming guidelines. Apart from that, backward compatibility should be guaranteed.

Hope this will make your life easier :)

Cheers,
Marco

**Comment by MichaelRoeder** [comment]
Hi Marco,

thank you very much for this work. It makes our work much easier ;)

Unfortunately, I couldn't find it in the central repository: http://search.maven.org/#search%7Cga%7C1%7Cit.unipi.di.acube
Am I searching in the wrong repo?

Cheers,
Michael

**Comment by marcocor** [comment]
Hi Michael,
indeed there was a synchronization problem with the Maven Central repository (heck, publishing something there is HARD). The package is now available for download.

(Maven's search engine may have not have indexed it yet.)

**Comment by MichaelRoeder** [comment]
Done.
