### ISSUE TITLE
Whose peanuts belong to GERBIL?

### ISSUE THREAD

**Issue by aolieman** [AKSW/gerbil#91]
Is the following phrase meant to be part of the introduction?
"[This is GERBIL. All your peanuts belong to me!](https://github.com/AKSW/gerbil/blob/9a2f39a21a01d91dfa68b88b1abc7b030335ff9c/src/main/webapp/WEB-INF/views/index.jsp#L18)"

It looks more like a placeholder that hasn't been removed yet.
P.S. the reference to All Your Base is much appreciated.

**Comment by RicardoUsbeck** [comment]
It is meant to be a funny joke :D 

For great justice
Ricardo
