### ISSUE TITLE
Configuration of the list of the datasets/annotators

### ISSUE THREAD

**Issue by MichaelRoeder** [AKSW/gerbil#92]
We have to decide how we want to make the list of datasets/annotators configurable in a better way.

### Current handling

At the moment, the list of annotators as well as the list of datasets are both hard coded. There are two classes, namely `DatasetMapping` and `AnnotatorMapping`, that generate a mapping between dataset/annotator names to configuration classes used for loading the dataset/annotator.

Advantages
- Well, it is working...

Disadvantages
- Adding or removing an adapter to the system has to be done by manipulating the mapping classes and recompiling the whole system.

We would like to change this implementation. But for this, we will have to decide in which direction GERBIL should be developed.

### Solution 1: Spring

We already created a prototype that uses the *magic* of the Spring framework to load the adapters (see the https://github.com/AKSW/gerbil/tree/springifyAdapterLoading branch).

The configuration classes of an adapter get a special annotation that contains the meta data that is needed by GERBIL.
```Java
@GerbilAnnotator(name = "AGDISTIS", couldBeCached = true, applicableForExperiments = ExperimentType.D2KB)
public class AgdistisAnnotator extends Annotator {
    ...
}
```
During the start up of the server, we are using the Spring framework to search for classes marked with these annotations. Thus, we are able to identify adapter classes and load their meta data from the annotations.

Advantages
- Adding a new adapter is very easy. Just add the annotation to your class and make sure, the class is inside a package in which we are searching for adapters (the list of these packages can be edited in the configuration file).

Disadvantages
- To remove an adapter from the list you might have to remove the annotation from its source code and recompile the project.

### Solution 2: Property files

It would be possible to configure the list of adapters using property files.
```
org.aksw.gerbil.annotator.class.AGDISTIS = org.aksw.gerbil.annotators.AgdistisAnnotator
org.aksw.gerbil.annotator.type = D2KB
org.aksw.gerbil.annotator.name = AGDISTIS
...
```

Advantages
- Adding and removing an adapter is easy.

Disadvantages
- There is no compiler taking care of the correct writing of classes or enum values. Thus, it is very easy to create a bugged property file.
- We have to find a way, how we can enable a NIF-based annotator to have different URLs for different tasks.

**Comment by RicardoUsbeck** [comment]
Personally, I am a friend of the SPRING version since it follows a clear paradigm and syntax checking.  I would prefer a solution, where adding/editing exactly one class in GERBIL is equal to adding one annotator/dataset.

**Comment by MichaelRoeder** [comment]
Axel said: Advantage of config files: No extra framework to integrate. Solution 2 seems to be good.

**Comment by MichaelRoeder** [comment]
One class for one annotator/dataset is not really good. Think of the NIF-file-based datasets or the different types of AIDA and Micropost datasets. Every of these datasets would need an own class even if these classes won't add functionality.

But you are raising an important point: In both solution it must be possible to use a single class for representing all AIDA datasets. I already implemented this for solution 1.
Solution 2 would need the possibility to define constructor arguments, e.g., a simple String argument, that can be used for adapters like the AIDA adapter or the file-based NIF adapter.

What do you think?

**Comment by MichaelRoeder** [comment]
The properties file based approach has been implemented and is working.
Thanks for the discussion!
