### ISSUE TITLE
DBpedia Spotlight returns HTTP 400

### ISSUE THREAD

**Issue by MichaelRoeder** [AKSW/gerbil#99]
In some rare cases the DBpedia Spotlight service returns an HTTP 400 error code. For example, this has been observed in a D2KB experiment using the IITB dataset.

**Comment by dav009** [comment]
can you share one of the cases here ?

**Comment by MichaelRoeder** [comment]
We could identify the problem. While we encoded the text itself, we missed to encode the surface forms. Here is an example for a text that created an HTTP error:
```XML
<?xml version="1.0" encoding="UTF-8"?>
<annotation text="++++Updated%3A+New+York...">
	...
	<surfaceForm name="Merrill Lynch & Co." offset="2161" />
</annotation>
```
